Repository megalodon-chess/megalodon, pull requests merged in 2021-04, with the labels that each got.

#60 Transposition Table
  src/options.cpp
  src/options.hpp
  src/search.cpp
  src/search.hpp
Labels: search

#62 Hash Table Compression
  src/bitboard.hpp
  src/options.cpp
  src/options.hpp
  src/search.cpp
  src/search.hpp
  src/uci.cpp
Labels: enhancement, search

#65 Arjun patch 1
  src/uci.cpp
Labels: enhancement

#66 Patrick Patch 3
  README.md
  docs/compiling.md
  src/bitboard.cpp
  src/bitboard.hpp
  src/debug.hpp
Labels: enhancement

#67 Arjun patch 2
  src/bitboard.cpp
  src/eval.cpp
  src/perft.cpp
  src/uci.cpp
  tests/randpos.py
Labels: enhancement

#69 Endgame
  src/endgame.cpp
  src/endgame.hpp
  src/eval.cpp
  src/search.cpp
  src/uci.cpp
Labels: enhancement, eval

#73 Tests
  tests/lichess_daily_puzzle.py
Labels: enhancement

#78 Compiler Warnings
  CMakeLists.txt
  src/bitboard.cpp
  src/bitboard.hpp
  src/endgame.cpp
  src/eval.cpp
  src/hash.cpp
  src/main.cpp
  src/options.cpp
  src/search.cpp
  src/uci.cpp
  src/utils.cpp
Labels: enhancement

#77 Eval Optimization
  src/eval.cpp
Labels: enhancement, eval

#83 Pseudo random gen
  src/main.cpp
  src/random.cpp
  src/random.hpp
  src/utils.cpp
Labels: enhancement
